### PR TITLE
fix(service): restart service if config changes

### LINKED ISSUE #37: [BUG] Service is not restarted on configuration change.
### Formula commit hash / release tag
Formula - from branch

### Versions reports (master & minion)

```
Salt Version:
           Salt: 3000
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.9 (default, Nov  7 2019, 10:44:02)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 5.4.18-1-MANJARO
         system: Linux
        version: Ubuntu 18.04 bionic
 
```

### Pillar / config used

---

### Describe the bug

Case is simple: configuration file has changed but service was not restarted.

### PR DESCRIPTION
**Pull request by kleinstuff**
* fixes #37

### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [x] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Comment by myii** [comment]
@kleinstuff Thanks for this.  As I mentioned in https://github.com/saltstack-formulas/keepalived-formula/pull/38#issuecomment-597489434, it should be sufficient to change the `require` to `watch`.  Can you try that and then modify this PR if that's the case?

**Comment by kleinstuff** [comment]
I don't think change require to watch is the correct way to do it.

Require == will set clearly that we *need* the config file in place to be
able to run the service
Watch == Restart if that config file is changed

I think we need both.

--
Att...

Ricardo Felipe Klein <https://www.linkedin.com/in/ricardo-klein-14982422>
klein.rfk@gmail.com

**Comment by cr1st1p** [comment]
I also think that you need both require and watch. First time when started, you would want the service to be started *after* (thus 'require') the config file present.

**Comment by myii** [comment]
https://docs.saltstack.com/en/latest/ref/states/requisites.html

> like require, but adds additional behaviour (mod_watch)

**Comment by kleinstuff** [comment]
ok... so...
just waiting the merge to happen, to finish this one...
next one will be a formula for openvpn and, later I will need to use the
zabbix formula (and I think I saw one or 2 things to fix already hehhe)



--
Att...

Ricardo Felipe Klein <https://www.linkedin.com/in/ricardo-klein-14982422>
klein.rfk@gmail.com

**Comment by kleinstuff** [comment]
but in that watch I did, we are watching the state, not a single file...
so, if later we add more files to the config state, all of them are already
"monitored".


--
Att...

Ricardo Felipe Klein <https://www.linkedin.com/in/ricardo-klein-14982422>
klein.rfk@gmail.com

**Comment by myii** [comment]
@kleinstuff The `commitlint` choked on the [second commit message](https://travis-ci.com/github/saltstack-formulas/keepalived-formula/jobs/316059004#L384-L392) so I just fixed it when squash-merging this PR.  Thanks again for fix!  And thanks to @cr1st1p for pointing this out in the first place in #37 and suggesting a fix in #38.

**Comment by myii** [comment]
The initial bug was introduced from the `template-formula`, so I've proposed the fix there as well:

* https://github.com/saltstack-formulas/template-formula/pull/193

**Pull request merged**
