### PR TITLE
Update of the keepalived config generator.  

### PR DESCRIPTION
**Pull request by jebas**

### CODE REVIEW

**Comment by gravyboat** [comment]
@bigbosst This is a pretty big change from what you contributed, could you please review this?

**Comment by jebas** [comment]
I left the commits in so you could follow how I created the template.

**Comment by gravyboat** [comment]
@jebas Thanks! I'm just not very familiar with this formula which is why I asked @bigbosst to review it.

**Comment by jebas** [comment]
Since this is still open, is there anything that I can do to make everyone more comfortable with my changes?

**Comment by gravyboat** [comment]
@jebas Nope I'll get it merged since no one else has commented, worse case we can always back it out, or they can make an updated PR to fix issues.

**Pull request merged**
