### PR TITLE
fix(service): restart service if configuration change (#37)

### PR DESCRIPTION
**Pull request by cr1st1p**
### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [x] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Related issues and/or pull requests

#37 

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Comment by myii** [comment]
@cr1st1p Thanks for this PR.  Could this be resolved by simply changing the following line to `- watch:` instead?

https://github.com/saltstack-formulas/keepalived-formula/blob/61e434475dd4575ce97ea0b70af22400a29c9bc6/keepalived/service/running.sls#L16

Could you test that at your end since you already have the failing situation?  If this is the problem, then a similar change needs to be made to the `template-formula`.

**Comment by kleinstuff** [comment]
Hi, 
I really didn't understood why you added so much code to the formula just to restart the service if the config changes, I have created a new PR with less code [here](https://github.com/saltstack-formulas/keepalived-formula/pull/41)
I tested and it works. So I think we can merge my PR and close this one here.

**Comment by cr1st1p** [comment]
If you tested your PR and it works, feel free to merge that one and I will close this one.

**Comment by myii** [comment]
> If you tested your PR and it works, feel free to merge that one and I will close this one.

Thanks, closing.

**Pull request closed without merging**
