### PR TITLE
Creates a human readable, tested, config file that fixes issue #12

### PR DESCRIPTION
**Pull request by jebas**

### CODE REVIEW

**Comment by kense2660** [comment]
We've tested this and it's working as expected. This fixes our issue in #12

**Comment by jebas** [comment]
Can someone please accept this pull request?

**Comment by jebas** [comment]
Once this is pull is accepted,  I have a small correction to the human readable formatting, followed by a small refactor.  The configuration file is still usable; it just doesn't look as nice.

**Comment by jebas** [comment]
@gravyboat Can you look at this pull request?

**Comment by gravyboat** [comment]
@jebas I can't do merges any longer since I stepped down from the org. Let's give @whiteinge a shout.

**Comment by whiteinge** [comment]
Thanks, @jebas!

**Pull request merged**
